<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Alexander | Portafolio</title>
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      background-color: #f4f4f4;
      color: #333;
    }
    header {
      background-color: #2c3e50;
      padding: 20px;
      color: white;
      text-align: center;
    }
    section {
      padding: 30px;
      max-width: 800px;
      margin: auto;
    }
    .card {
      background: white;
      margin: 20px 0;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .project-link {
      color: #3498db;
      text-decoration: none;
      font-weight: bold;
    }
    footer {
      background-color: #2c3e50;
      color: white;
      text-align: center;
      padding: 10px;
      font-size: 0.9em;
    }
  </style>
</head>
<body>

  <header>
    <h1>Alexander M치rquez</h1>
    <p>Ingeniero Industrial | Desarrollador Python | An치lisis de Datos</p>
  </header>

  <section>
    <h2>游꿢 Sobre m칤</h2>
    <div class="card">
      <p>Apasionado por la tecnolog칤a y el desarrollo web. Tengo experiencia en Python, Flask y automatizaci칩n, as칤 como en an치lisis de datos para la toma de decisiones. En este portafolio encontrar치s algunos de mis proyectos destacados.</p>
    </div>

    <h2>游빌 Proyectos</h2>
    <div class="card">
      <h3>游꿚 Plataforma de efectos de audio</h3>
      <p>Desarrollo web completo con login, subida de archivos, pagos y panel administrativo. Ideal para vender efectos de sonido digitales.</p>
      <a href="https://github.com/MathError21/audio-market" class="project-link" target="_blank">Ver en GitHub</a>
    </div>

    <div class="card">
      <h3>游늵 Dashboard de An치lisis de Costos</h3>
      <p>Herramienta en Python que analiza componentes e insumos industriales, con visualizaci칩n interactiva y correlaci칩n de datos.</p>
      <a href="#" class="project-link" target="_blank">Pr칩ximamente</a>
    </div>
  </section>

  <footer>
    춸 2025 Alexander M치rquez 췅 matherror21.github.io
  </footer>

</body>
</html>

